# Generated by Django 3.0.5 on 2020-05-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Toppings'},
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='text',
        ),
    ]
