# Generated by Django 3.0.6 on 2020-05-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pizza',
            new_name='Pizza',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='pizza',
            new_name='Pizza',
        ),
    ]
