# Generated by Django 3.0.6 on 2020-05-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20200506_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Pizza',
            new_name='pizza',
        ),
    ]
