# Generated by Django 3.0.6 on 2020-05-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_pizza_pizza_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_img',
        ),
    ]
