# Generated by Django 3.0.6 on 2020-05-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_remove_pizza_pizza_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='Pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Topping'),
            preserve_default=False,
        ),
    ]
