# Generated by Django 3.0.6 on 2020-05-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20200506_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.AddField(
            model_name='topping',
            name='Pizza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza'),
            preserve_default=False,
        ),
    ]
